# MetricsTracker Demo (TT-31 + TT-37)

Demonstrates the position metrics engine joining live DXLink Quote and Greeks
data with account positions. Loads positions via REST, subscribes to DXLink for
streamer symbols, and displays the joined DataFrame with live Greeks for options
and theoretical defaults for delta-1 instruments.

In [1]:
import asyncio
import logging
import os

import pandas as pd
from dotenv import load_dotenv
from IPython.display import Markdown, display

from tastytrade.accounts import AccountsClient
from tastytrade.analytics.metrics import DELTA_1_TYPES, OPTION_TYPES, MetricsTracker
from tastytrade.config import RedisConfigManager
from tastytrade.config.enumerations import Channels
from tastytrade.connections import Credentials
from tastytrade.connections.requests import AsyncSessionHandler
from tastytrade.connections.sockets import DXLinkManager
from tastytrade.messaging.processors.metrics import MetricsEventProcessor

pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", 40)

load_dotenv("/workspace/.env", override=True)

logging.basicConfig(level=logging.INFO)
logging.getLogger("websockets").setLevel(logging.WARNING)

_OBFUSCATE = os.getenv("OBFUSCATE_ACCOUNTS", "false").lower() == "true"


def mask(account_number: str) -> str:
    if not _OBFUSCATE or len(account_number) <= 4:
        return account_number
    return "***" + account_number[-4:]


print(f"Account obfuscation: {'ON' if _OBFUSCATE else 'OFF'}")

Account obfuscation: ON

# 1. Connect & Fetch Positions

In [2]:
config = RedisConfigManager(env_file="/workspace/.env")
config.initialize(force=True)

credentials = Credentials(config=config, env="Live")
session = await AsyncSessionHandler.create(credentials)
client = AccountsClient(session)

account = credentials.account_number
positions = await client.get_positions(account)

display(Markdown(f"**{len(positions)} positions** in account {mask(account)}"))

pos_summary = [{
    "Symbol": p.symbol,
    "Type": p.instrument_type.value,
    "Qty": p.quantity,
    "Direction": p.quantity_direction.value,
    "Streamer": p.streamer_symbol,
} for p in positions]
display(pd.DataFrame(pos_summary))

INFO:tastytrade.config.manager:Initialized 53 variables from .env file in Redis
INFO:tastytrade.connections.auth:Session created via OAuth2
INFO:tastytrade.accounts.client:Fetched 26 positions for account 5WY89822

**26 positions** in account ***9822

,Symbol,Type,Qty,Direction,Streamer
0,./ZBM6 OZBJ6 260327P115,Future Option,1.00,Short,./OZBJ26P115:XCBT
1,./RTYM6RTMH6 260331C2875,Future Option,1.00,Long,./RTMH26C2875:XCME
2,./MCLJ6MW4G6 260227C65.5,Future Option,1.00,Short,./MW4G26C65.5:XNYM
3,./ZBM6 OZBJ6 260327C120.5,Future Option,1.00,Short,./OZBJ26C120.5:XCBT
4,./MESM6EXH6 260331C7250,Future Option,1.00,Short,./EXH26C7250:XCME
5,./MESM6EXH6 260331P6575,Future Option,1.00,Short,./EXH26P6575:XCME
6,./MCLJ6MW4G6 260227P65.5,Future Option,1.00,Short,./MW4G26P65.5:XNYM
7,CSCO 260402C00083000,Equity Option,1.00,Short,.CSCO260402C83
8,SPY 260402P00661000,Equity Option,1.00,Long,.SPY260402P661
9,SPY 260402P00666000,Equity Option,1.00,Short,.SPY260402P666
10,SPY 260402C00705000,Equity Option,1.00,Short,.SPY260402C705
11,QQQ 260402C00635000,Equity Option,1.00,Short,.QQQ260402C635
12,QQQ 260402P00585000,Equity Option,1.00,Short,.QQQ260402P585
13,QQQ 260402P00580000,Equity Option,1.00,Long,.QQQ260402P580
14,./RTYM6RTMH6 260331P2390,Future Option,1.00,Long,./RTMH26P2390:XCME
15,./RTYM6RTMH6 260331C2825,Future Option,1.00,Short,./RTMH26C2825:XCME
16,./RTYM6RTMH6 260331P2425,Future Option,1.00,Short,./RTMH26P2425:XCME
17,./6EM6 EUUJ6 260403C1.215,Future Option,2.00,Short,./EUUJ26C1.215:XCME
18,./6EM6 EUUJ6 260403P1.16,Future Option,2.00,Short,./EUUJ26P1.16:XCME
19,./GCJ6 OGJ6 260326C5740,Future Option,1.00,Short,./OGJ26C5740:XCEC
20,./GCJ6 OGJ6 260326C5760,Future Option,1.00,Long,./OGJ26C5760:XCEC
21,./GCJ6 OGJ6 260326P4600,Future Option,1.00,Long,./OGJ26P4600:XCEC
22,./GCJ6 OGJ6 260326P4620,Future Option,1.00,Short,./OGJ26P4620:XCEC
23,SPY,Equity,101.29,Long,SPY
24,CSCO,Equity,103.56,Long,NaN
25,QQQ,Equity,100.13,Long,QQQ

# 2. Initialize MetricsTracker

In [3]:
tracker = MetricsTracker()
tracker.load_positions(positions)

streamer_symbols = tracker.get_streamer_symbols()
option_symbols = tracker.get_option_streamer_symbols()
skipped = [p.symbol for p in positions if p.streamer_symbol is None]

display(Markdown(f"**Tracking {len(tracker.securities)} securities** ({len(skipped)} skipped — no streamer symbol)"))
display(Markdown(f"**{len(option_symbols)} option symbols** for Greeks channel: `{sorted(option_symbols)}`"))
if skipped:
    print(f"Skipped: {skipped}")

display(Markdown("**Initial state (no market data yet):**"))
display(tracker.df[["symbol", "instrument_type", "quantity", "quantity_direction",
                     "bid_price", "ask_price", "mid_price",
                     "delta", "gamma", "theta", "vega"]])

INFO:tastytrade.analytics.metrics:Loaded 26 positions (26 with streamer symbols)

**Tracking 26 securities** (1 skipped — no streamer symbol)

**23 option symbols** for Greeks channel: `['./EUUJ26C1.215:XCME', './EUUJ26P1.16:XCME', './EXH26C7250:XCME', './EXH26P6575:XCME', './MW4G26C65.5:XNYM', './MW4G26P65.5:XNYM', './OGJ26C5740:XCEC', './OGJ26C5760:XCEC', './OGJ26P4600:XCEC', './OGJ26P4620:XCEC', './OZBJ26C120.5:XCBT', './OZBJ26P115:XCBT', './RTMH26C2825:XCME', './RTMH26C2875:XCME', './RTMH26P2390:XCME', './RTMH26P2425:XCME', '.CSCO260402C83', '.QQQ260402C635', '.QQQ260402P580', '.QQQ260402P585', '.SPY260402C705', '.SPY260402P661', '.SPY260402P666']`

Skipped: ['CSCO']

**Initial state (no market data yet):**

,symbol,instrument_type,quantity,quantity_direction,bid_price,ask_price,mid_price,delta,gamma,theta,vega
0,./ZBM6 OZBJ6 260327P115,Future Option,1.00,Short,None,None,None,NaN,NaN,NaN,NaN
1,./RTYM6RTMH6 260331C2875,Future Option,1.00,Long,None,None,None,NaN,NaN,NaN,NaN
2,./MCLJ6MW4G6 260227C65.5,Future Option,1.00,Short,None,None,None,NaN,NaN,NaN,NaN
3,./ZBM6 OZBJ6 260327C120.5,Future Option,1.00,Short,None,None,None,NaN,NaN,NaN,NaN
4,./MESM6EXH6 260331C7250,Future Option,1.00,Short,None,None,None,NaN,NaN,NaN,NaN
5,./MESM6EXH6 260331P6575,Future Option,1.00,Short,None,None,None,NaN,NaN,NaN,NaN
6,./MCLJ6MW4G6 260227P65.5,Future Option,1.00,Short,None,None,None,NaN,NaN,NaN,NaN
7,CSCO 260402C00083000,Equity Option,1.00,Short,None,None,None,NaN,NaN,NaN,NaN
8,SPY 260402P00661000,Equity Option,1.00,Long,None,None,None,NaN,NaN,NaN,NaN
9,SPY 260402P00666000,Equity Option,1.00,Short,None,None,None,NaN,NaN,NaN,NaN
10,SPY 260402C00705000,Equity Option,1.00,Short,None,None,None,NaN,NaN,NaN,NaN
11,QQQ 260402C00635000,Equity Option,1.00,Short,None,None,None,NaN,NaN,NaN,NaN
12,QQQ 260402P00585000,Equity Option,1.00,Short,None,None,None,NaN,NaN,NaN,NaN
13,QQQ 260402P00580000,Equity Option,1.00,Long,None,None,None,NaN,NaN,NaN,NaN
14,./RTYM6RTMH6 260331P2390,Future Option,1.00,Long,None,None,None,NaN,NaN,NaN,NaN
15,./RTYM6RTMH6 260331C2825,Future Option,1.00,Short,None,None,None,NaN,NaN,NaN,NaN
16,./RTYM6RTMH6 260331P2425,Future Option,1.00,Short,None,None,None,NaN,NaN,NaN,NaN
17,./6EM6 EUUJ6 260403C1.215,Future Option,2.00,Short,None,None,None,NaN,NaN,NaN,NaN
18,./6EM6 EUUJ6 260403P1.16,Future Option,2.00,Short,None,None,None,NaN,NaN,NaN,NaN
19,./GCJ6 OGJ6 260326C5740,Future Option,1.00,Short,None,None,None,NaN,NaN,NaN,NaN
20,./GCJ6 OGJ6 260326C5760,Future Option,1.00,Long,None,None,None,NaN,NaN,NaN,NaN
21,./GCJ6 OGJ6 260326P4600,Future Option,1.00,Long,None,None,None,NaN,NaN,NaN,NaN
22,./GCJ6 OGJ6 260326P4620,Future Option,1.00,Short,None,None,None,NaN,NaN,NaN,NaN
23,SPY,Equity,101.29,Long,None,None,None,1.0,0.0,0.0,0.0
24,CSCO,Equity,103.56,Long,None,None,None,1.0,0.0,0.0,0.0
25,QQQ,Equity,100.13,Long,None,None,None,1.0,0.0,0.0,0.0

# 3. Open DXLink & Attach MetricsEventProcessor

In [ ]:
dxlink = DXLinkManager()
await dxlink.open(credentials=credentials)

router = dxlink.router
if router is None:
    raise RuntimeError("DXLink router not initialized")

processor = MetricsEventProcessor(tracker)

# Attach to Quote handler (prices)
quote_handler = router.handler.get(Channels.Quote)
if quote_handler is None:
    raise RuntimeError("Quote handler not found")
quote_handler.add_processor(processor)

# Attach to Greeks handler (delta, gamma, theta, vega, rho, IV)
greeks_handler = router.handler.get(Channels.Greeks)
if greeks_handler is None:
    raise RuntimeError("Greeks handler not found")
greeks_handler.add_processor(processor)

print(f"MetricsEventProcessor attached to Quote and Greeks handlers")
print(f"Quote handler processors: {list(quote_handler.processors.keys())}")
print(f"Greeks handler processors: {list(greeks_handler.processors.keys())}")

INFO:tastytrade.connections.auth:Session created via OAuth2
INFO:tastytrade.messaging.handlers:Started Channels.Control listener on channel 0
INFO:tastytrade.messaging.handlers:Started Channels.Quote listener on channel 7
INFO:tastytrade.messaging.handlers:Started Channels.Trade listener on channel 5
INFO:tastytrade.messaging.handlers:Started Channels.Greeks listener on channel 11
INFO:tastytrade.messaging.handlers:Started Channels.Profile listener on channel 1
INFO:tastytrade.messaging.handlers:Started Channels.Summary listener on channel 3
INFO:tastytrade.messaging.handlers:Started Channels.Candle listener on channel 9

MetricsEventProcessor attached to Quote and Greeks handlers
Quote handler processors: ['feed', 'metrics']
Greeks handler processors: ['feed', 'metrics']

INFO:tastytrade.messaging.handlers:SETUP
INFO:tastytrade.messaging.handlers:AUTH_STATE:AUTHORIZED
INFO:tastytrade.messaging.handlers:CHANNEL_OPENED:1
INFO:tastytrade.messaging.handlers:CHANNEL_OPENED:3
INFO:tastytrade.messaging.handlers:CHANNEL_OPENED:5
INFO:tastytrade.messaging.handlers:CHANNEL_OPENED:7
INFO:tastytrade.messaging.handlers:CHANNEL_OPENED:9
INFO:tastytrade.messaging.handlers:CHANNEL_OPENED:11
INFO:tastytrade.messaging.handlers:CHANNEL_OPENED:99
INFO:tastytrade.messaging.handlers:FEED_CONFIG:5:COMPACT
INFO:tastytrade.messaging.handlers:FEED_CONFIG:7:COMPACT
INFO:tastytrade.messaging.handlers:FEED_CONFIG:11:COMPACT
INFO:tastytrade.messaging.handlers:FEED_CONFIG:1:COMPACT
INFO:tastytrade.messaging.handlers:FEED_CONFIG:3:COMPACT
INFO:tastytrade.messaging.handlers:FEED_CONFIG:9:COMPACT
INFO:tastytrade.messaging.handlers:FEED_CONFIG:5:COMPACT:SUBSCRIBED
INFO:tastytrade.messaging.handlers:FEED_CONFIG:7:COMPACT:SUBSCRIBED
INFO:tastytrade.messaging.handlers:FEED_CONFIG:11:COMPACT:SUBSCRIBED
INFO:tastytrade.messaging.handlers:FEED_CONFIG:1:COMPACT:SUBSCRIBED
INFO:tastytrade.messaging.handlers:FEED_CONFIG:3:COMPACT:SUBSCRIBED
INFO:tastytrade.connections.sockets:Websocket listener stopped
INFO:tastytrade.connections.sockets:Keepalive stopped
INFO:tastytrade.messaging.handlers:Control listener stopped for channel 0
INFO:tastytrade.messaging.handlers:Channel 0 metrics - Total messages: 21, Errors: 0, Max queue size: 5
INFO:tastytrade.messaging.handlers:Quote listener stopped for channel 7
INFO:tastytrade.messaging.handlers:Channel 7 metrics - Total messages: 41, Errors: 0, Max queue size: 1
INFO:tastytrade.messaging.handlers:Trade listener stopped for channel 5
INFO:tastytrade.messaging.handlers:Channel 5 metrics - Total messages: 11, Errors: 0, Max queue size: 2
INFO:tastytrade.messaging.handlers:Greeks listener stopped for channel 11
INFO:tastytrade.messaging.handlers:Channel 11 metrics - Total messages: 8, Errors: 0, Max queue size: 1
INFO:tastytrade.messaging.handlers:Profile listener stopped for channel 1
INFO:tastytrade.messaging.handlers:Channel 1 metrics - Total messages: 13, Errors: 0, Max queue size: 8
INFO:tastytrade.messaging.handlers:Summary listener stopped for channel 3
INFO:tastytrade.messaging.handlers:Channel 3 metrics - Total messages: 6, Errors: 0, Max queue size: 4
INFO:tastytrade.messaging.handlers:Candle listener stopped for channel 9
INFO:tastytrade.messaging.handlers:Channel 9 metrics - Total messages: 0, Errors: 0, Max queue size: 0

# 4. Subscribe to Position Streamer Symbols

In [5]:
symbols_list = sorted(streamer_symbols)
print(f"Subscribing to {len(symbols_list)} symbols:")
for s in symbols_list:
    print(f"  {s}")

await dxlink.subscribe(symbols_list)
print(f"\nSubscribed. Waiting for quotes to flow...")

INFO:tastytrade.connections.sockets:Added subscription: ./EUUJ26C1.215:XCME
INFO:tastytrade.connections.sockets:Added subscription: ./EUUJ26P1.16:XCME
INFO:tastytrade.connections.sockets:Added subscription: ./EXH26C7250:XCME
INFO:tastytrade.connections.sockets:Added subscription: ./EXH26P6575:XCME
INFO:tastytrade.connections.sockets:Added subscription: ./MW4G26C65.5:XNYM
INFO:tastytrade.connections.sockets:Added subscription: ./MW4G26P65.5:XNYM
INFO:tastytrade.connections.sockets:Added subscription: ./OGJ26C5740:XCEC
INFO:tastytrade.connections.sockets:Added subscription: ./OGJ26C5760:XCEC
INFO:tastytrade.connections.sockets:Added subscription: ./OGJ26P4600:XCEC
INFO:tastytrade.connections.sockets:Added subscription: ./OGJ26P4620:XCEC
INFO:tastytrade.connections.sockets:Added subscription: ./OZBJ26C120.5:XCBT
INFO:tastytrade.connections.sockets:Added subscription: ./OZBJ26P115:XCBT
INFO:tastytrade.connections.sockets:Added subscription: ./RTMH26C2825:XCME
INFO:tastytrade.connections.sockets:Added subscription: ./RTMH26C2875:XCME
INFO:tastytrade.connections.sockets:Added subscription: ./RTMH26P2390:XCME
INFO:tastytrade.connections.sockets:Added subscription: ./RTMH26P2425:XCME
INFO:tastytrade.connections.sockets:Added subscription: .CSCO260402C83
INFO:tastytrade.connections.sockets:Added subscription: .QQQ260402C635
INFO:tastytrade.connections.sockets:Added subscription: .QQQ260402P580
INFO:tastytrade.connections.sockets:Added subscription: .QQQ260402P585
INFO:tastytrade.connections.sockets:Added subscription: .SPY260402C705
INFO:tastytrade.connections.sockets:Added subscription: .SPY260402P661
INFO:tastytrade.connections.sockets:Added subscription: .SPY260402P666
INFO:tastytrade.connections.sockets:Added subscription: CSCO
INFO:tastytrade.connections.sockets:Added subscription: QQQ
INFO:tastytrade.connections.sockets:Added subscription: SPY

Subscribing to 26 symbols:
  ./EUUJ26C1.215:XCME
  ./EUUJ26P1.16:XCME
  ./EXH26C7250:XCME
  ./EXH26P6575:XCME
  ./MW4G26C65.5:XNYM
  ./MW4G26P65.5:XNYM
  ./OGJ26C5740:XCEC
  ./OGJ26C5760:XCEC
  ./OGJ26P4600:XCEC
  ./OGJ26P4620:XCEC
  ./OZBJ26C120.5:XCBT
  ./OZBJ26P115:XCBT
  ./RTMH26C2825:XCME
  ./RTMH26C2875:XCME
  ./RTMH26P2390:XCME
  ./RTMH26P2425:XCME
  .CSCO260402C83
  .QQQ260402C635
  .QQQ260402P580
  .QQQ260402P585
  .SPY260402C705
  .SPY260402P661
  .SPY260402P666
  CSCO
  QQQ
  SPY

Subscribed. Waiting for quotes to flow...

# 5. View Live Metrics

Re-run this cell to see updated prices and Greeks as data arrives.

In [6]:
await asyncio.sleep(3)  # allow quotes to arrive

df = tracker.df

# Reorder columns for readability
display_cols = [
    "symbol", "instrument_type", "quantity", "quantity_direction",
    "bid_price", "ask_price", "mid_price",
    "delta", "gamma", "theta", "vega", "implied_volatility",
    "price_updated_at",
]
available_cols = [c for c in display_cols if c in df.columns]

populated = df["bid_price"].notna().sum()
display(Markdown(f"**{populated}/{len(df)} securities** have live quote data"))
display(df[available_cols])

**26/26 securities** have live quote data

,symbol,instrument_type,quantity,quantity_direction,bid_price,ask_price,mid_price,delta,gamma,theta,vega,implied_volatility,price_updated_at
0,./ZBM6 OZBJ6 260327P115,Future Option,1.00,Short,0.27,0.30,0.29,-0.18,0.10,-0.01,0.09,0.08,2026-02-26 00:37:03.752328
1,./RTYM6RTMH6 260331C2875,Future Option,1.00,Long,7.90,8.80,8.35,0.12,0.00,-0.44,1.61,0.19,2026-02-26 00:37:03.776169
2,./MCLJ6MW4G6 260227C65.5,Future Option,1.00,Short,1.25,1.40,1.32,0.55,0.13,-0.31,0.02,0.62,2026-02-26 00:37:03.754718
3,./ZBM6 OZBJ6 260327C120.5,Future Option,1.00,Short,0.22,0.25,0.23,0.15,0.08,-0.01,0.08,0.09,2026-02-26 00:37:03.756660
4,./MESM6EXH6 260331C7250,Future Option,1.00,Short,16.40,19.60,18.00,0.15,0.00,-0.80,5.06,0.11,2026-02-26 00:37:03.755128
5,./MESM6EXH6 260331P6575,Future Option,1.00,Short,37.00,38.00,37.50,-0.15,0.00,-1.58,5.05,0.21,2026-02-26 00:37:03.755903
6,./MCLJ6MW4G6 260227P65.5,Future Option,1.00,Short,0.97,1.12,1.04,-0.45,0.13,-0.31,0.02,0.62,2026-02-26 00:37:03.754926
7,CSCO 260402C00083000,Equity Option,1.00,Short,0.73,1.02,0.88,0.26,0.06,-0.03,0.08,0.23,2026-02-26 00:37:03.763834
8,SPY 260402P00661000,Equity Option,1.00,Long,5.05,5.10,5.07,-0.21,0.01,-0.17,0.63,0.19,2026-02-26 00:37:03.753612
9,SPY 260402P00666000,Equity Option,1.00,Short,5.75,5.80,5.78,-0.24,0.01,-0.18,0.68,0.19,2026-02-26 00:37:03.753863
10,SPY 260402C00705000,Equity Option,1.00,Short,6.51,6.56,6.54,0.34,0.01,-0.14,0.79,0.13,2026-02-26 00:37:03.753304
11,QQQ 260402C00635000,Equity Option,1.00,Short,6.39,6.59,6.49,0.29,0.01,-0.16,0.66,0.17,2026-02-26 00:37:03.752618
12,QQQ 260402P00585000,Equity Option,1.00,Short,6.50,6.65,6.58,-0.24,0.01,-0.20,0.60,0.24,2026-02-26 00:37:03.753090
13,QQQ 260402P00580000,Equity Option,1.00,Long,5.71,5.87,5.79,-0.21,0.01,-0.19,0.56,0.25,2026-02-26 00:37:03.752853
14,./RTYM6RTMH6 260331P2390,Future Option,1.00,Long,10.60,11.40,11.00,-0.09,0.00,-0.59,1.35,0.30,2026-02-26 00:37:03.764098
15,./RTYM6RTMH6 260331C2825,Future Option,1.00,Short,16.00,17.10,16.55,0.20,0.00,-0.63,2.27,0.19,2026-02-26 00:37:03.763393
16,./RTYM6RTMH6 260331P2425,Future Option,1.00,Short,13.40,14.10,13.75,-0.11,0.00,-0.68,1.58,0.29,2026-02-26 00:37:03.763612
17,./6EM6 EUUJ6 260403C1.215,Future Option,2.00,Short,0.00,0.00,0.00,0.15,8.91,-0.00,0.00,0.07,2026-02-26 00:37:08.305016
18,./6EM6 EUUJ6 260403P1.16,Future Option,2.00,Short,0.00,0.00,0.00,-0.12,8.39,-0.00,0.00,0.06,2026-02-26 00:37:08.305589
19,./GCJ6 OGJ6 260326C5740,Future Option,1.00,Short,37.30,40.10,38.70,0.15,0.00,-1.99,3.43,0.33,2026-02-26 00:37:06.997974
20,./GCJ6 OGJ6 260326C5760,Future Option,1.00,Long,35.20,38.00,36.60,0.15,0.00,-1.94,3.35,0.34,2026-02-26 00:37:07.200585
21,./GCJ6 OGJ6 260326P4600,Future Option,1.00,Long,20.90,22.70,21.80,-0.09,0.00,-1.44,2.45,0.34,2026-02-26 00:37:07.201187
22,./GCJ6 OGJ6 260326P4620,Future Option,1.00,Short,22.50,24.40,23.45,-0.10,0.00,-1.50,2.58,0.34,2026-02-26 00:37:06.797637
23,SPY,Equity,101.29,Long,692.28,692.35,692.32,1.00,0.00,0.00,0.00,NaN,2026-02-26 00:37:07.862090
24,CSCO,Equity,103.56,Long,79.05,79.43,79.24,1.00,0.00,0.00,0.00,NaN,2026-02-26 00:37:03.754076
25,QQQ,Equity,100.13,Long,615.00,615.10,615.05,1.00,0.00,0.00,0.00,NaN,2026-02-26 00:37:08.097236

# 6. Delta-1 vs Options Greeks Comparison

Delta-1 products have theoretical defaults (delta=+/-1, gamma/theta/vega/rho=0).
Options have live Greeks populated from the DXLink Greeks channel.

In [7]:
df = tracker.df

delta1_mask = df["instrument_type"].isin([t.value for t in DELTA_1_TYPES])
option_mask = df["instrument_type"].isin([t.value for t in OPTION_TYPES])

greeks_cols = ["symbol", "instrument_type", "delta", "gamma", "theta", "vega", "rho", "implied_volatility", "greeks_updated_at"]

display(Markdown("**Delta-1 positions** (theoretical Greeks):"))
display(df.loc[delta1_mask, greeks_cols])

display(Markdown("**Option positions** (live Greeks from DXLink):"))
display(df.loc[option_mask, greeks_cols])

**Delta-1 positions** (theoretical Greeks):

,symbol,instrument_type,delta,gamma,theta,vega,rho,implied_volatility,greeks_updated_at
23,SPY,Equity,1.0,0.0,0.0,0.0,0.0,NaN,2026-02-26 00:36:57.616033
24,CSCO,Equity,1.0,0.0,0.0,0.0,0.0,NaN,2026-02-26 00:36:57.616033
25,QQQ,Equity,1.0,0.0,0.0,0.0,0.0,NaN,2026-02-26 00:36:57.616033

**Option positions** (live Greeks from DXLink):

,symbol,instrument_type,delta,gamma,theta,vega,rho,implied_volatility,greeks_updated_at
0,./ZBM6 OZBJ6 260327P115,Future Option,-0.18,0.10,-0.01,0.09,-0.02,0.08,2026-02-26 00:37:03.757774
1,./RTYM6RTMH6 260331C2875,Future Option,0.12,0.00,-0.44,1.61,0.28,0.19,2026-02-26 00:37:03.776485
2,./MCLJ6MW4G6 260227C65.5,Future Option,0.55,0.13,-0.31,0.02,0.00,0.62,2026-02-26 00:37:03.760391
3,./ZBM6 OZBJ6 260327C120.5,Future Option,0.15,0.08,-0.01,0.08,0.01,0.09,2026-02-26 00:37:03.761800
4,./MESM6EXH6 260331C7250,Future Option,0.15,0.00,-0.80,5.06,0.98,0.11,2026-02-26 00:37:03.760925
5,./MESM6EXH6 260331P6575,Future Option,-0.15,0.00,-1.58,5.05,-1.03,0.21,2026-02-26 00:37:03.760088
6,./MCLJ6MW4G6 260227P65.5,Future Option,-0.45,0.13,-0.31,0.02,-0.00,0.62,2026-02-26 00:37:03.760686
7,CSCO 260402C00083000,Equity Option,0.26,0.06,-0.03,0.08,0.02,0.23,2026-02-26 00:37:03.764421
8,SPY 260402P00661000,Equity Option,-0.21,0.01,-0.17,0.63,-0.15,0.19,2026-02-26 00:37:04.166861
9,SPY 260402P00666000,Equity Option,-0.24,0.01,-0.18,0.68,-0.17,0.19,2026-02-26 00:37:05.007728
10,SPY 260402C00705000,Equity Option,0.34,0.01,-0.14,0.79,0.22,0.13,2026-02-26 00:37:05.316581
11,QQQ 260402C00635000,Equity Option,0.29,0.01,-0.16,0.66,0.17,0.17,2026-02-26 00:37:03.758034
12,QQQ 260402P00585000,Equity Option,-0.24,0.01,-0.20,0.60,-0.15,0.24,2026-02-26 00:37:03.758541
13,QQQ 260402P00580000,Equity Option,-0.21,0.01,-0.19,0.56,-0.13,0.25,2026-02-26 00:37:03.758290
14,./RTYM6RTMH6 260331P2390,Future Option,-0.09,0.00,-0.59,1.35,-0.24,0.30,2026-02-26 00:37:03.765212
15,./RTYM6RTMH6 260331C2825,Future Option,0.20,0.00,-0.63,2.27,0.48,0.19,2026-02-26 00:37:03.764681
16,./RTYM6RTMH6 260331P2425,Future Option,-0.11,0.00,-0.68,1.58,-0.30,0.29,2026-02-26 00:37:03.764912
17,./6EM6 EUUJ6 260403C1.215,Future Option,0.15,8.91,-0.00,0.00,0.00,0.07,2026-02-26 00:37:03.759594
18,./6EM6 EUUJ6 260403P1.16,Future Option,-0.12,8.39,-0.00,0.00,-0.00,0.06,2026-02-26 00:37:03.759841
19,./GCJ6 OGJ6 260326C5740,Future Option,0.15,0.00,-1.99,3.43,0.60,0.33,2026-02-26 00:37:03.761296
20,./GCJ6 OGJ6 260326C5760,Future Option,0.15,0.00,-1.94,3.35,0.57,0.34,2026-02-26 00:37:03.761550
21,./GCJ6 OGJ6 260326P4600,Future Option,-0.09,0.00,-1.44,2.45,-0.40,0.34,2026-02-26 00:37:03.757262
22,./GCJ6 OGJ6 260326P4620,Future Option,-0.10,0.00,-1.50,2.58,-0.43,0.34,2026-02-26 00:37:03.757520

# 7. Cleanup

In [8]:
await dxlink.close()
await session.close()
print("All connections closed.")

INFO:tastytrade.connections.sockets:Listener task cancelled
INFO:tastytrade.connections.sockets:Keepalive task cancelled
INFO:tastytrade.connections.routing:Initiating cleanup...
INFO:tastytrade.connections.routing:Cleanup completed
WARNING:tastytrade.connections.requests:Failed to terminate session: HTTP 403
INFO:tastytrade.connections.requests:Session closed
INFO:tastytrade.connections.sockets:Connection closed and cleaned up
WARNING:tastytrade.connections.requests:Failed to terminate session: HTTP 403
INFO:tastytrade.connections.requests:Session closed

All connections closed.